### ISSUE TITLE
Websockets issues 

### ISSUE THREAD

**Issue by jbucky86** [W3AXL/python-radio-console#15]
I can only connect to my radios on my local machine and not a client machine I believe it is due to websockets not being secure. Am I doing something wrong?

**Comment by W3AXL** [comment]
You're correct. To use websockets & WebRTC, you have to be connected to a website via HTTPS

Please see the wiki section for HTTPS setup: https://github.com/W3AXL/python-radio-console/wiki/Setup#https-certificates-for-a-locally-hosted-server

**Comment by dreinhold** [comment]
@jbucky86 I just got it working on a remote machine, here is what I had to do.

- When starting the app you need to pass `--a 0.0.0.0` this will make the web app listen on all addresses on the machine not just local loopback
- In my browser I had to allow mixed mode secure and non secure for the page, this link was helpful in that https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html?lang=en
-

**Comment by jbucky86** [comment]
@dreinhold yes I did this not a remote machine but I did assume this would work but did not test it as I really want my remote machine to be a mobile device.

**Comment by W3AXL** [comment]
Depending on your mobile device, I believe you could set up a trusted certificate via the settings. I know on Apple devices you can trust custom root certificates (if I'm remembering correctly).

Although I will caution you that I haven't ever tested the console on a mobile device. The entire project is still very early in development. I've been focusing on hardware designs recently to make interfacing with radios easier, but it's taking a while to get that done and I can't do much more development on the software until I have more radios to use.

**Comment by dreinhold** [comment]
@jbucky86 you can try this [pull/17](https://github.com/W3AXL/python-radio-console/pull/17) I am now able to use it from my phone.
